export const projects = [
  {
    id: 0,
    slug: "instagram-business-scraper-api",
    image: "/images/InstagramScraperAPI_edit.PNG",
    tags: [
      "Python",
      "FastAPI",
      "AsyncIO",
      "SQLAlchemy",
      "Instaloader",
      "PayPal API",
      "JWT",
    ],
    source: "https://riandrydevelop.github.io/instagram_scraper_api_public/",
  },
  {
    id: 1,
    slug: "sismo-app",
    image: "/images/SismoApp_edit.PNG",
    tags: [
      "React",
      "Vite",
      "TailwindCSS",
      "Ruby on Rails",
      "REST API",
      "SQLite3",
      "Playwright",
    ],
    source: "https://riandrydevelop.github.io/SismoUI",
  },
  {
    id: 2,
    slug: "library-app-mobile",
    image: "/images/LibraryAPP_edit.PNG",
    tags: ["React Native", "Node.js", "Express", "Firebase"],
    source: "https://github.com/RiandryDevelop/LibraryAppUI",
  },
  {
    id: 3,
    slug: "the-roulette-game",
    image: "/images/RouletteGame_edit.PNG",
    tags: [
      "Vue 3",
      "TypeScript",
      "Pinia",
      ".NET",
      "SQL Server",
      "Docker",
      "GameDev",
    ],
    source:
      "https://github.com/RiandryDevelop/Prueba-Tecnica-RiandryConnor-El-Juego-de-la-Ruleta",
  },
];
